// Generated by CoffeeScript 1.3.3
(function() {
  var PORT, app, express, nib, stylus;

  PORT = process.env.PORT || 3000;

  express = require('express');

  stylus = require('stylus');

  nib = require('nib');

  app = express();

  app.configure(function() {
    app.use(stylus.middleware({
      src: 'public',
      compile: function(str, path) {
        return stylus(str).use(nib())["import"]('nib').set('filename', path);
      }
    }));
    app.use(express["static"](__dirname + '/public'));
    return app.use(express["static"](__dirname + '/components'));
  });

  app.listen(PORT, function() {
    return console.log("RUNNING " + PORT);
  });

}).call(this);
